import { test, expect } from '@playwright/test';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';

/**
 * OTP E2E tests.
 *
 * Rather than driving the full signup form (which involves file upload to R2),
 * these tests seed a PENDING_VERIFICATION user and a VerificationToken directly
 * in the isolated local database. This keeps the test deterministic and avoids
 * coupling OTP-flow coverage to the R2 document-upload path.
 *
 * The staging-e2e.spec.ts file owns the full signup form E2E coverage.
 */

const db = new PrismaClient();

function hashToken(token: string): string {
  return crypto.createHash('sha256').update(token).digest('hex');
}

test.describe('Email Verification OTP', () => {
  // Unique per run to avoid conflicts when the DB is reused between retries
  const email = `otp-test-${Date.now()}@example.com`;
  const password = 'Password123!';
  let validOtp = '';

  test.beforeAll(async () => {
    // Guard: never run against production
    const url = process.env.DATABASE_URL ?? '';
    if (!url.includes('localhost') && !url.includes('127.0.0.1') && !url.includes('e2e_db')) {
      throw new Error('OTP tests must not run against a non-local database.');
    }

    const passwordHash = await bcrypt.hash(password, 10);

    // Clean up any leftover from a previous interrupted run
    await db.verificationToken.deleteMany({ where: { identifier: `verify_${email}` } });
    await db.user.deleteMany({ where: { email } });

    // Seed: PENDING_VERIFICATION user
    await db.user.create({
      data: {
        email,
        name: 'OTP Test User',
        passwordHash,
        role: 'USER',
        status: 'PENDING_VERIFICATION',
      },
    });

    // Seed: a valid VerificationToken (15-minute expiry)
    validOtp = crypto.randomInt(0, 1_000_000).toString().padStart(6, '0');
    const hashedOtp = hashToken(validOtp);
    await db.verificationToken.create({
      data: {
        identifier: `verify_${email}`,
        token: hashedOtp,
        expires: new Date(Date.now() + 15 * 60 * 1_000),
      },
    });
  });

  test.afterAll(async () => {
    // Cleanup test fixtures
    await db.verificationToken.deleteMany({ where: { identifier: `verify_${email}` } }).catch(() => {});
    await db.user.deleteMany({ where: { email } }).catch(() => {});
    await db.$disconnect();
  });

  // I. Unverified account cannot log in
  test('I. Unverified login is rejected', async ({ page }) => {
    await page.goto('/login');
    await page.fill('input[name="email"]', email);
    await page.fill('input[name="password"]', password);
    await page.click('button[type="submit"]');

    // Login page always shows "Invalid email or password." for any rejection
    // (including PENDING_VERIFICATION) to prevent account-enumeration.
    await expect(page.locator('text=Invalid email or password.')).toBeVisible({ timeout: 10_000 });

    // Must remain on login — not redirected to dashboard
    expect(page.url()).toMatch(/\/login/);
  });

  // C. Wrong OTP shows error
  test('C. Wrong OTP is rejected on the verify-email page', async ({ page }) => {
    await page.goto(`/verify-email?email=${encodeURIComponent(email)}`);

    await page.fill('input[name="otp"]', '000000');
    await page.click('button[type="submit"]');

    // The form shows result.error from the server action ("Invalid token")
    // or the fallback "Invalid or expired OTP."
    const errorDiv = page.locator('div.text-red-600');
    await expect(errorDiv).toBeVisible({ timeout: 10_000 });
    const errorText = await errorDiv.textContent();
    expect(errorText).toBeTruthy(); // any non-empty error is correct rejection behaviour
  });

  // B/D. Resend OTP sends a new code
  test('G/H. Resend OTP sends a new token and enforces cooldown', async ({ page }) => {
    await page.goto(`/verify-email?email=${encodeURIComponent(email)}`);

    // Click Resend
    await page.click('button:has-text("Resend OTP")');

    // Success message
    await expect(page.locator('text=A new OTP has been sent')).toBeVisible({ timeout: 10_000 });

    // Cooldown button should now be disabled with remaining seconds label
    await expect(page.locator('button', { hasText: /Resend OTP in/ })).toBeDisabled({ timeout: 5_000 });
  });

  // E. Correct OTP verifies the account
  test('E. Correct OTP verifies the account and redirects to login', async ({ page }) => {
    // Fetch the latest token seeded in beforeAll (or regenerated by Resend in previous test)
    // Re-seed to ensure we have a known OTP regardless of prior test ordering
    const knownOtp = crypto.randomInt(0, 1_000_000).toString().padStart(6, '0');
    const hashedOtp = hashToken(knownOtp);
    await db.verificationToken.deleteMany({ where: { identifier: `verify_${email}` } });
    await db.verificationToken.create({
      data: {
        identifier: `verify_${email}`,
        token: hashedOtp,
        expires: new Date(Date.now() + 15 * 60 * 1_000),
      },
    });

    await page.goto(`/verify-email?email=${encodeURIComponent(email)}`);
    await page.fill('input[name="otp"]', knownOtp);
    await page.click('button[type="submit"]');

    await expect(page.locator('text=Email verified successfully')).toBeVisible({ timeout: 10_000 });

    // Redirects to /login after 1.5s delay
    await expect(page).toHaveURL(/\/login/, { timeout: 10_000 });

    // User should now be ACTIVE in DB
    const user = await db.user.findUnique({ where: { email }, select: { status: true } });
    expect(user?.status).toBe('ACTIVE');
  });

  // M. Duplicate signup preserves anti-enumeration: redirects to /verify-email as if successful
  test('M. Duplicate signup is anti-enumerated (redirects to verify-email)', async ({ page }) => {
    await page.goto('/signup');

    // Use a *different* existing email (the owner) to test anti-enumeration without relying on file upload
    // The registerUser action silently returns success for existing emails
    const existingEmail = process.env.OWNER_EMAIL ?? 'uniqueowner123@test.com';

    await page.fill('input[name="email"]', existingEmail);
    await page.fill('input[name="password"]', 'Password123!');
    await page.fill('input[name="firstName"]', 'Test');
    await page.fill('input[name="lastName"]', 'User');
    await page.selectOption('select[name="idProofType"]', 'PAN');
    await page.fill('input[name="idProofNumber"]', 'ABCDE1234F');
    await page.setInputFiles('input[name="idProofFile"]', {
      name: 'id.jpg',
      mimeType: 'image/jpeg',
      buffer: Buffer.from([0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01]),
    });
    await page.fill('input[name="dateOfBirth"]', '1990-01-01');
    await page.selectOption('select[name="gender"]', 'Male');
    await page.fill('textarea[name="serviceAddress"]', '123 Test St');
    await page.fill('input[name="mobileNumber"]', '9999999999');
    await page.fill('input[name="bloodGroup"]', 'O+');
    await page.fill('input[name="sponsorName"]', 'Sponsor');
    await page.fill('input[name="sponsorRelationship"]', 'Friend');
    await page.fill('input[name="sponsorMobile"]', '8888888888');
    await page.check('input[type="checkbox"]');
    await page.click('button[type="submit"]');

    // Anti-enumeration: for existing emails, the action returns success immediately
    // without touching R2, so the redirect is fast.
    await expect(page).toHaveURL(/\/verify-email\?email=/, { timeout: 30_000 });
  });
});
