export const PERMISSIONS = {
  // Members
  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_CREATE: 'MEMBER_CREATE',
  MEMBER_EDIT: 'MEMBER_EDIT',
  MEMBER_SENSITIVE_VIEW: 'MEMBER_SENSITIVE_VIEW',

  // Employees
  EMPLOYEE_VIEW: 'EMPLOYEE_VIEW',
  EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
  EMPLOYEE_EDIT: 'EMPLOYEE_EDIT',
  EMPLOYEE_DEACTIVATE: 'EMPLOYEE_DEACTIVATE',

  // Payments
  PAYMENT_VIEW: 'PAYMENT_VIEW',
  PAYMENT_VERIFY: 'PAYMENT_VERIFY',

  // Invoices
  INVOICE_VIEW: 'INVOICE_VIEW',
  INVOICE_MANAGE: 'INVOICE_MANAGE',

  // Plans
  PLAN_VIEW: 'PLAN_VIEW',
  PLAN_MANAGE: 'PLAN_MANAGE',

  // Custom Plans
  CUSTOM_PLAN_VIEW: 'CUSTOM_PLAN_VIEW',
  CUSTOM_PLAN_CREATE: 'CUSTOM_PLAN_CREATE',
  CUSTOM_PLAN_EDIT: 'CUSTOM_PLAN_EDIT',
  CUSTOM_PLAN_APPROVE: 'CUSTOM_PLAN_APPROVE',

  // Renewals
  RENEWAL_VIEW: 'RENEWAL_VIEW',
  RENEWAL_APPROVE: 'RENEWAL_APPROVE',

  // Inquiries
  INQUIRY_VIEW: 'INQUIRY_VIEW',
  INQUIRY_MANAGE: 'INQUIRY_MANAGE',

  // Feedback
  FEEDBACK_VIEW: 'FEEDBACK_VIEW',
  FEEDBACK_MANAGE: 'FEEDBACK_MANAGE',

  // Audits
  AUDIT_VIEW: 'AUDIT_VIEW',

  // Admin Users
  ADMIN_USER_VIEW: 'ADMIN_USER_VIEW',
  ADMIN_USER_MANAGE: 'ADMIN_USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE',

  // Care Operations (Phase 17)
  CARE_CASE_VIEW: 'CARE_CASE_VIEW',
  CARE_CASE_CREATE: 'CARE_CASE_CREATE',
  CARE_CASE_MANAGE: 'CARE_CASE_MANAGE',
  CARE_ASSIGNMENT_VIEW: 'CARE_ASSIGNMENT_VIEW',
  CARE_ASSIGNMENT_MANAGE: 'CARE_ASSIGNMENT_MANAGE',
  CARE_VISIT_VIEW: 'CARE_VISIT_VIEW',
  CARE_VISIT_MANAGE: 'CARE_VISIT_MANAGE',
  CARE_TASK_VIEW: 'CARE_TASK_VIEW',
  CARE_TASK_MANAGE: 'CARE_TASK_MANAGE',
  CARE_NOTE_VIEW: 'CARE_NOTE_VIEW',
  CARE_NOTE_CREATE: 'CARE_NOTE_CREATE',
  CARE_NOTE_MANAGE: 'CARE_NOTE_MANAGE',
  CARE_RESTRICTED_NOTE_VIEW: 'CARE_RESTRICTED_NOTE_VIEW',
} as const;

export type PermissionCode = keyof typeof PERMISSIONS;
